# Generated by Django 5.0.3 on 2024-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uz',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
